### ISSUE TITLE
Bug na ExperienceBar

### ISSUE THREAD

**Issue by djonibourscheid** [alexandredev3/moveit-nlw4#1]
### Explicação
Quando um usuário entra pela primeira vez, os valores dos cookies demoram para carregar ou algo do gênero, e os valores de `width` e `left`  que são calculados com os valores dos cookies bugam e resultam em NaN.

### Correção
Se definir no css dos elementos o `width: 0` e `left: 0` respectivamente, já resolve.

---
Se quiser testar, abre a [aplicação](https://moveit-alexandredev3.vercel.app) em uma nova janela no modo anônimo que já aparece

**Comment by djonibourscheid** [comment]
Com um projeto usando o `module.css` é mais fácil de mostrar...
![image](https://user-images.githubusercontent.com/62856037/109395213-eb0b8780-7909-11eb-80c9-3e1e2c94f1e7.png)

Até onde eu sei, o erro só acontece na primeira vez que o usuário entra, então nas próximas visitas o `width: 0` será simplesmente pulado

**Comment by alexandredev3** [comment]
> Com um projeto usando o `module.css` é mais fácil de mostrar...
> ![image](https://user-images.githubusercontent.com/62856037/109395213-eb0b8780-7909-11eb-80c9-3e1e2c94f1e7.png)
> 
> Até onde eu sei, o erro só acontece na primeira vez que o usuário entra, então nas próximas visitas o `width: 0` será simplesmente pulado

Extamente, podemos corrigir esse bug fazendo o seguinte:

Vamos remover aquelas validações nos estados do ```ChallengeContext```
```
// Causa o bug na ExpirenceBar
const [level, setLevel] = useState(rest.level ?? 1);
const [currentExperience, setCurrentExperience] = useState(rest.currentExperience ?? 1);
const [challengesCompleted, setChallengesCompleted] = useState(rest.challengesCompleted ?? 1);
const [activeChallenge, setActiveChallenge] = useState<IChallenge | null>(null);
const [isLevelUpModalOpen, setIsModalLevelUpOpen] = useState(false);
```

Validações removidas fica assim:
```
const [level, setLevel] = useState(rest.level);
const [currentExperience, setCurrentExperience] = useState(rest.currentExperience);
const [challengesCompleted, setChallengesCompleted] = useState(rest.challengesCompleted);
const [activeChallenge, setActiveChallenge] = useState<IChallenge | null>(null);
const [isLevelUpModalOpen, setIsModalLevelUpOpen] = useState(false);
```

Agora vamos fazer essas validações antes de rendelizar a página, no ```getServerSideProps```
```
export const getServerSideProps: GetServerSideProps = async (context) => {
  const { req } = context;

  const { level, currentExperience, challengesCompleted } = req.cookies;

  return {
    props: {
     // aqui >
      level: Number(level ?? 1),
      currentExperience: Number(currentExperience ?? 0),
      challengesCompleted: Number(challengesCompleted ?? 0),
    }
  }
}
```

Bug corrigido no commit [0903e35a4ba58a1aef136d6562db2ee91ddbd297](https://github.com/alexandredev3/moveit-nlw4/commit/0903e35a4ba58a1aef136d6562db2ee91ddbd297)
**Muito Obrigado por sua contribuição!! :heart:**
